/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0849afa1-6266-4553-baa4-ac1444f680c0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_KTOl2zyZQ",
    "aws_user_pools_web_client_id": "33d5lskfd6us0gs300k3hgi9bp",
    "oauth": {}
};


export default awsmobile;
